
[[main]]
  name = "Project"
  url = "/project/overview"
  weight = 10
  #pre = "<i class='fa-solid fa-clipboard-question mr-1'></i>"

[[main]]
  parent = "Project"
  name = "Overview"
  url = "/project/overview/"
  weight = 10

[[main]]
  parent = "Project"
  name = "Case studies"
  url = "/project/case-studies/"
  weight = 20

[[main]]
  parent = "Overview"
  name = "Maps"
  url = "/project/overview/maps/"
  weight = 30

[[main]]
  parent = "Overview"
  name = "Screenshots"
  url = "/project/overview/screenshots/"
  weight = 30  

[[main]]
  parent = "Project"
  name = "Plugins"
  url = "https://plugins.qgis.org"
  weight = 30

[[main]]
  parent = "Project"
  name = "Visual Changelogs"
  url = "/project/visual-changelogs"
  weight = 40


[[main]]
  name = "Community"
  url = "/community/involve"
  weight = 20

[[main]]
  parent = "Community"
  name = "Get involved"
  url = "/community/involve"
  weight = 10

[[main]]
  parent = "Community"
  name = "Certification Programme"
  url = "/community/certification"
  weight = 20

[[main]]
  parent = "Community"
  name = "QGIS Foundation"
  url = "/community/foundation"
  weight = 30

[[main]]
  parent = "QGIS Foundation"
  name = "Charter"
  url = "/community/foundation/charter"
  weight = 40

[[main]]
  parent = "QGIS Foundation"
  name = "Annual General Meetings"
  url = "/community/foundation/annual_general_meetings"
  weight = 50

[[main]]
  parent = "QGIS Foundation"
  name = "Annual Reports"
  url = "/community/foundation/annual_reports"
  weight = 60

[[main]]
  parent = "QGIS Foundation"
  name = "Finance"
  url = "/community/foundation/finance"
  weight = 70

[[main]]
  parent = "Community"
  name = "Project Organisation"
  url = "/community/organisation"
  weight = 80


[[main]]
  parent = "Project Organisation"
  name = "Infrastructure"
  url = "/community/organisation/infrastructure"
  weight = 100

[[main]]
  parent = "Community"
  name = "Local User Groups"
  url = "/community/groups"
  weight = 110



[[main]]
  parent = "Project Organisation"
  name = "Brand Guidelines"
  url = "/community/organisation/guidelines"
  weight = 130

[[main]]
  parent = "Project Organisation"
  name = "Contributor Credits"
  url = "/community/organisation/credits"
  weight = 140

[[main]]
  parent = "Project Organisation"
  name = "Meetings"
  url = "/community/organisation/meetings"
  weight = 180

[[main]]
  parent = "Meetings"
  name = "QGIS Developer Meetings"
  url = "/community/organisation/meetings/dev_meetings"
  weight = 190

[[main]]
  parent = "Meetings"
  name = "Reimbursements for Developer Meetings"
  url = "/community/organisation/meetings/reimbursements"
  weight = 200

[[main]]
  parent = "Meetings"
  name = "QGIS User Meetings"
  url = "/community/organisation/meetings/user_meetings"
  weight = 210

[[main]]
  parent = "Project Organisation"
  name = "Mailing Lists"
  url = "/community/organisation/mailinglists"
  weight = 220
  
[[main]]
  parent = "Community"
  name = "Members Blogs"
  url = "https://plugins.qgis.org/planet/"
  weight = 280

[[main]]
  name = "Resources"
  url = "/resources/hub"
  weight = 40 # Sets the menu order 
  #pre = "<i class='fa-solid fa-handshake-angle mr-1'></i>"

[[main]]
  parent = "Resources"
  name = "Documentation"
  url = "/resources/hub"
  weight = 5 # Sets the menu order 
  #pre = "<i class='fa-solid fa-handshake-angle mr-1'></i>"  


[[main]]
  # parent = "Funding"
  name = "Goodies"
  url = "/goodies"
  weight = 60

[[main]]
  name = "Download"
  url = "/download/"
  #pre = "<i class='fa-solid fa-circle-down mr-1'></i>"
  weight = 80 # Sets the menu order 

[[main]]
  name = "Archive"
  url = "/archive/"
  #pre = "<i class='fa-solid fa-circle-down mr-1'></i>"
  weight = 90 # Sets the menu order 

[[main]]
  name = "Funding"
  url = "/funding/donate"
  #pre = "<i class='fa-solid fa-circle-down mr-1'></i>"
  weight = 50 # Sets the menu order 

[[main]]
  parent = "Funding"
  name = "Donate"
  url = "/funding/donate"
  #pre = "<i class='fa-solid fa-circle-down mr-1'></i>"
  weight = 30 # Sets the menu order 

[[main]]
  parent = "Funding"
  name = "Membership"
  url = "/funding/membership"
  weight = 230

[[main]]
  parent = "Membership"
  name = "Members"
  url = "/funding/membership/members"
  weight = 240


[[main]]
  parent = "Membership"
  name = "Past Members"
  url = "/funding/membership/past_members"
  weight = 260

[[main]]
  parent = "Donate"
  name = "Donors"
  url = "/funding/donate/donors"
  weight = 270

# Submenus are done this way: parent -> identifier
[[main]]
  parent = "Resources"
  name = "Installation guide"
  url = "/resources/installation-guide/"
  weight = 10


[[main]]
  parent = "Resources"
  name = "Testing"
  url = "/resources/testing/"
  weight = 30

[[main]]
  parent = "Resources"
  name = "Roadmap"
  url = "/resources/roadmap/"
  weight = 40

[[main]]
  parent = "Resources"
  name = "Reports"
  url = "/resources/reports/"
  weight = 50

[[main]]
  parent = "Reports"
  name = "OGC Certification"
  url = "/resources/reports/#ogc-certification"
  weight = 60

[[main]]
  parent = "Reports"
  name = "Performance"
  url = "/resources/reports/#performance"
  weight = 70

[[main]]
  parent = "Reports"
  name = "Security"
  url = "/resources/reports/#security"
  weight = 80

[[main]]
  parent = "Resources"
  name = "Books"
  url = "/resources/books/"
  weight = 90

[[main]]
  parent = "Resources"
  name = "Support"
  url = "/resources/support/"
  weight = 100

[[main]]
  parent = "Support"
  name = "FAQ"
  url = "/resources/support/faq"
  weight = 110

[[main]]
  parent = "Support"
  name = "Bug Reporting"
  url = "/resources/support/bug-reporting"
  weight = 120

[[main]]
  parent = "Support"
  name = "Communication channels"
  url = "/resources/support/#communication-channels"
  weight = 130

[[main]]
  parent = "Support"
  name = "Commercial support"
  url = "/resources/support/commercial-support"
  weight = 140

[[main]]
  parent = "Support"
  name = "StackExchange"
  url = "/resources/support/#stackexchange"
  weight = 160

[[main]]
  parent = "Resources"
  name = "QGIS Metrics"
  url = "https://analytics.qgis.org"
  weight = 180

[[main]]
  parent = "Resources"
  name = "Plugins Metrics"
  url = "https://plugins.qgis.org/metabase/public/dashboard/7ecd345f-7321-423d-9844-71e526a454a9"
  weight = 190

[[main]]
  parent = "Resources"
  name = "Blog"
  url = "https://blog.qgis.org/"
  weight = 200

[[main]]
  parent = "Support"
  name = "Security"
  url = "/resources/support/security"
  weight = 190
